//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MgooGps.POIService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="POIService.POIServiceSoap")]
    public interface POIServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 MapType 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAddressByLatlng", ReplyAction="*")]
        MgooGps.POIService.GetAddressByLatlngResponse GetAddressByLatlng(MgooGps.POIService.GetAddressByLatlngRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAddressByLatlngRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAddressByLatlng", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.POIService.GetAddressByLatlngRequestBody Body;
        
        public GetAddressByLatlngRequest() {
        }
        
        public GetAddressByLatlngRequest(MgooGps.POIService.GetAddressByLatlngRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAddressByLatlngRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal Lat;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public decimal Lng;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MapType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Language;
        
        public GetAddressByLatlngRequestBody() {
        }
        
        public GetAddressByLatlngRequestBody(decimal Lat, decimal Lng, string MapType, string Language) {
            this.Lat = Lat;
            this.Lng = Lng;
            this.MapType = MapType;
            this.Language = Language;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAddressByLatlngResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAddressByLatlngResponse", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.POIService.GetAddressByLatlngResponseBody Body;
        
        public GetAddressByLatlngResponse() {
        }
        
        public GetAddressByLatlngResponse(MgooGps.POIService.GetAddressByLatlngResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAddressByLatlngResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAddressByLatlngResult;
        
        public GetAddressByLatlngResponseBody() {
        }
        
        public GetAddressByLatlngResponseBody(string GetAddressByLatlngResult) {
            this.GetAddressByLatlngResult = GetAddressByLatlngResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface POIServiceSoapChannel : MgooGps.POIService.POIServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class POIServiceSoapClient : System.ServiceModel.ClientBase<MgooGps.POIService.POIServiceSoap>, MgooGps.POIService.POIServiceSoap {
        
        public POIServiceSoapClient() {
        }
        
        public POIServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public POIServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public POIServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public POIServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MgooGps.POIService.GetAddressByLatlngResponse MgooGps.POIService.POIServiceSoap.GetAddressByLatlng(MgooGps.POIService.GetAddressByLatlngRequest request) {
            return base.Channel.GetAddressByLatlng(request);
        }
        
        public string GetAddressByLatlng(decimal Lat, decimal Lng, string MapType, string Language) {
            MgooGps.POIService.GetAddressByLatlngRequest inValue = new MgooGps.POIService.GetAddressByLatlngRequest();
            inValue.Body = new MgooGps.POIService.GetAddressByLatlngRequestBody();
            inValue.Body.Lat = Lat;
            inValue.Body.Lng = Lng;
            inValue.Body.MapType = MapType;
            inValue.Body.Language = Language;
            MgooGps.POIService.GetAddressByLatlngResponse retVal = ((MgooGps.POIService.POIServiceSoap)(this)).GetAddressByLatlng(inValue);
            return retVal.Body.GetAddressByLatlngResult;
        }
    }
}
