//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MG_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyRecord
    {
        public int BuyID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> DeviceID { get; set; }
        public string OrderNumber { get; set; }
        public string OpenID { get; set; }
        public Nullable<decimal> BuyMoney { get; set; }
        public Nullable<int> BuyDay { get; set; }
        public string PayMethod { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> OldExpireDate { get; set; }
        public Nullable<System.DateTime> NewExpireDate { get; set; }
        public string Remarks { get; set; }
    }
}
