//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MG_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarCommandQueue
    {
        public int ID { get; set; }
        public string DeviceID { get; set; }
        public string CommandText { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsSend { get; set; }
        public System.DateTime SendDate { get; set; }
        public Nullable<bool> IsResponse { get; set; }
        public Nullable<System.DateTime> ResponseDate { get; set; }
        public string ResponseText { get; set; }
        public string CommandName { get; set; }
        public Nullable<bool> IsOfflineSend { get; set; }
        public string Infos { get; set; }
        public Nullable<int> SendCount { get; set; }
    }
}
