//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MG_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevicesReport
    {
        public int ID { get; set; }
        public Nullable<int> DeviceID { get; set; }
        public Nullable<decimal> NowDistance { get; set; }
        public Nullable<decimal> AllDistance { get; set; }
        public Nullable<int> WarnCount { get; set; }
        public Nullable<int> SpeedLimitCount { get; set; }
        public Nullable<int> StopCount { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
