//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MG_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevTest
    {
        public int wxDevID { get; set; }
        public string wxIMEI { get; set; }
        public string wxName { get; set; }
        public Nullable<int> yxDevID { get; set; }
        public string yxIMEI { get; set; }
        public string yxName { get; set; }
    }
}
