//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MG_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileAppInfo
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> AppsID { get; set; }
        public string ClientID { get; set; }
        public string Token { get; set; }
        public string Model { get; set; }
        public string Vendor { get; set; }
        public string OS { get; set; }
        public string OSVersion { get; set; }
        public string IMEI { get; set; }
        public string UUID { get; set; }
        public string IMSI { get; set; }
        public string Resolution { get; set; }
        public string DPI { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public string APPVersion { get; set; }
    }
}
