//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MG_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int OrderID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> DeviceID { get; set; }
        public string OpenID { get; set; }
        public string OrderNo { get; set; }
        public string TransactionNo { get; set; }
        public string ProductBody { get; set; }
        public string FeeType { get; set; }
        public Nullable<int> TotalFee { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> OrderExpire { get; set; }
        public Nullable<System.DateTime> PayDate { get; set; }
        public string TradeType { get; set; }
        public string Status { get; set; }
        public string BankType { get; set; }
        public Nullable<int> TariffID { get; set; }
        public string BillCreateIP { get; set; }
    }
}
