//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MG_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpeedReport
    {
        public int SID { get; set; }
        public Nullable<int> DeviceID { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<int> TypeID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<decimal> OLat { get; set; }
        public Nullable<decimal> OLng { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<double> TimediffMinute { get; set; }
        public Nullable<decimal> SpeedLimit { get; set; }
    }
}
