//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MG_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersConfig
    {
        public int UserID { get; set; }
        public string PushMsgType { get; set; }
        public Nullable<bool> PushAudio { get; set; }
        public Nullable<bool> PushShock { get; set; }
        public Nullable<int> PushPeriod { get; set; }
        public Nullable<int> ShockSens { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
