//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MG_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeChatUsers
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string LoginName { get; set; }
        public string OpenID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string PushMsg { get; set; }
        public Nullable<bool> Deleted { get; set; }
    }
}
