//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MgooGps.UsersAjax {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UsersAjax.UsersAjaxSoap")]
    public interface UsersAjaxSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetZtreeResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetZtree", ReplyAction="*")]
        MgooGps.UsersAjax.GetZtreeResponse GetZtree(MgooGps.UsersAjax.GetZtreeRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 Pass 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidPassword", ReplyAction="*")]
        MgooGps.UsersAjax.ValidPasswordResponse ValidPassword(MgooGps.UsersAjax.ValidPasswordRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetLowerUsersResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLowerUsers", ReplyAction="*")]
        MgooGps.UsersAjax.GetLowerUsersResponse GetLowerUsers(MgooGps.UsersAjax.GetLowerUsersRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 UserName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveUsers", ReplyAction="*")]
        MgooGps.UsersAjax.SaveUsersResponse SaveUsers(MgooGps.UsersAjax.SaveUsersRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 FirstName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUser", ReplyAction="*")]
        MgooGps.UsersAjax.UpdateUserResponse UpdateUser(MgooGps.UsersAjax.UpdateUserRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 FirstName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUserInfo", ReplyAction="*")]
        MgooGps.UsersAjax.UpdateUserInfoResponse UpdateUserInfo(MgooGps.UsersAjax.UpdateUserInfoRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 OldPass 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateUserPass", ReplyAction="*")]
        MgooGps.UsersAjax.UpdateUserPassResponse UpdateUserPass(MgooGps.UsersAjax.UpdateUserPassRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 UserName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchUsers", ReplyAction="*")]
        MgooGps.UsersAjax.SearchUsersResponse SearchUsers(MgooGps.UsersAjax.SearchUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelUserById", ReplyAction="*")]
        int DelUserById(int UserID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InitUserPassword", ReplyAction="*")]
        int InitUserPassword(int UserID);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetUsersRelationByDeviceIDResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUsersRelationByDeviceID", ReplyAction="*")]
        MgooGps.UsersAjax.GetUsersRelationByDeviceIDResponse GetUsersRelationByDeviceID(MgooGps.UsersAjax.GetUsersRelationByDeviceIDRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 LoginName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserNameByLoginName", ReplyAction="*")]
        MgooGps.UsersAjax.GetUserNameByLoginNameResponse GetUserNameByLoginName(MgooGps.UsersAjax.GetUserNameByLoginNameRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetZtreeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetZtree", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.UsersAjax.GetZtreeRequestBody Body;
        
        public GetZtreeRequest() {
        }
        
        public GetZtreeRequest(MgooGps.UsersAjax.GetZtreeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetZtreeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int userID;
        
        public GetZtreeRequestBody() {
        }
        
        public GetZtreeRequestBody(int userID) {
            this.userID = userID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetZtreeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetZtreeResponse", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.UsersAjax.GetZtreeResponseBody Body;
        
        public GetZtreeResponse() {
        }
        
        public GetZtreeResponse(MgooGps.UsersAjax.GetZtreeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetZtreeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetZtreeResult;
        
        public GetZtreeResponseBody() {
        }
        
        public GetZtreeResponseBody(string GetZtreeResult) {
            this.GetZtreeResult = GetZtreeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidPassword", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.UsersAjax.ValidPasswordRequestBody Body;
        
        public ValidPasswordRequest() {
        }
        
        public ValidPasswordRequest(MgooGps.UsersAjax.ValidPasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidPasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Pass;
        
        public ValidPasswordRequestBody() {
        }
        
        public ValidPasswordRequestBody(int UserID, string Pass) {
            this.UserID = UserID;
            this.Pass = Pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidPasswordResponse", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.UsersAjax.ValidPasswordResponseBody Body;
        
        public ValidPasswordResponse() {
        }
        
        public ValidPasswordResponse(MgooGps.UsersAjax.ValidPasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidPasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ValidPasswordResult;
        
        public ValidPasswordResponseBody() {
        }
        
        public ValidPasswordResponseBody(int ValidPasswordResult) {
            this.ValidPasswordResult = ValidPasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLowerUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLowerUsers", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.UsersAjax.GetLowerUsersRequestBody Body;
        
        public GetLowerUsersRequest() {
        }
        
        public GetLowerUsersRequest(MgooGps.UsersAjax.GetLowerUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLowerUsersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int PageNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int PageCount;
        
        public GetLowerUsersRequestBody() {
        }
        
        public GetLowerUsersRequestBody(int UserID, int PageNo, int PageCount) {
            this.UserID = UserID;
            this.PageNo = PageNo;
            this.PageCount = PageCount;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLowerUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLowerUsersResponse", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.UsersAjax.GetLowerUsersResponseBody Body;
        
        public GetLowerUsersResponse() {
        }
        
        public GetLowerUsersResponse(MgooGps.UsersAjax.GetLowerUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLowerUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetLowerUsersResult;
        
        public GetLowerUsersResponseBody() {
        }
        
        public GetLowerUsersResponseBody(string GetLowerUsersResult) {
            this.GetLowerUsersResult = GetLowerUsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveUsers", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.UsersAjax.SaveUsersRequestBody Body;
        
        public SaveUsersRequest() {
        }
        
        public SaveUsersRequest(MgooGps.UsersAjax.SaveUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveUsersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ParentID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LoginName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Pass;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int UserType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string FirstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string CellPhone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Address;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int Status;
        
        public SaveUsersRequestBody() {
        }
        
        public SaveUsersRequestBody(int ParentID, string UserName, string LoginName, string Pass, int UserType, string FirstName, string CellPhone, string Address, int Status) {
            this.ParentID = ParentID;
            this.UserName = UserName;
            this.LoginName = LoginName;
            this.Pass = Pass;
            this.UserType = UserType;
            this.FirstName = FirstName;
            this.CellPhone = CellPhone;
            this.Address = Address;
            this.Status = Status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveUsersResponse", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.UsersAjax.SaveUsersResponseBody Body;
        
        public SaveUsersResponse() {
        }
        
        public SaveUsersResponse(MgooGps.UsersAjax.SaveUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SaveUsersResult;
        
        public SaveUsersResponseBody() {
        }
        
        public SaveUsersResponseBody(int SaveUsersResult) {
            this.SaveUsersResult = SaveUsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUser", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.UsersAjax.UpdateUserRequestBody Body;
        
        public UpdateUserRequest() {
        }
        
        public UpdateUserRequest(MgooGps.UsersAjax.UpdateUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int UserType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string FirstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CellPhone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Address;
        
        public UpdateUserRequestBody() {
        }
        
        public UpdateUserRequestBody(int UserID, int UserType, string FirstName, string CellPhone, string Address) {
            this.UserID = UserID;
            this.UserType = UserType;
            this.FirstName = FirstName;
            this.CellPhone = CellPhone;
            this.Address = Address;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.UsersAjax.UpdateUserResponseBody Body;
        
        public UpdateUserResponse() {
        }
        
        public UpdateUserResponse(MgooGps.UsersAjax.UpdateUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateUserResult;
        
        public UpdateUserResponseBody() {
        }
        
        public UpdateUserResponseBody(bool UpdateUserResult) {
            this.UpdateUserResult = UpdateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserInfo", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.UsersAjax.UpdateUserInfoRequestBody Body;
        
        public UpdateUserInfoRequest() {
        }
        
        public UpdateUserInfoRequest(MgooGps.UsersAjax.UpdateUserInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUserInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FirstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CellPhone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string TimeZone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int SendType;
        
        public UpdateUserInfoRequestBody() {
        }
        
        public UpdateUserInfoRequestBody(int UserID, string FirstName, string CellPhone, string Address, string TimeZone, string Email, int SendType) {
            this.UserID = UserID;
            this.FirstName = FirstName;
            this.CellPhone = CellPhone;
            this.Address = Address;
            this.TimeZone = TimeZone;
            this.Email = Email;
            this.SendType = SendType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.UsersAjax.UpdateUserInfoResponseBody Body;
        
        public UpdateUserInfoResponse() {
        }
        
        public UpdateUserInfoResponse(MgooGps.UsersAjax.UpdateUserInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUserInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateUserInfoResult;
        
        public UpdateUserInfoResponseBody() {
        }
        
        public UpdateUserInfoResponseBody(bool UpdateUserInfoResult) {
            this.UpdateUserInfoResult = UpdateUserInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserPassRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserPass", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.UsersAjax.UpdateUserPassRequestBody Body;
        
        public UpdateUserPassRequest() {
        }
        
        public UpdateUserPassRequest(MgooGps.UsersAjax.UpdateUserPassRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUserPassRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string OldPass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NewPass;
        
        public UpdateUserPassRequestBody() {
        }
        
        public UpdateUserPassRequestBody(int UserID, string OldPass, string NewPass) {
            this.UserID = UserID;
            this.OldPass = OldPass;
            this.NewPass = NewPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateUserPassResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateUserPassResponse", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.UsersAjax.UpdateUserPassResponseBody Body;
        
        public UpdateUserPassResponse() {
        }
        
        public UpdateUserPassResponse(MgooGps.UsersAjax.UpdateUserPassResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateUserPassResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdateUserPassResult;
        
        public UpdateUserPassResponseBody() {
        }
        
        public UpdateUserPassResponseBody(int UpdateUserPassResult) {
            this.UpdateUserPassResult = UpdateUserPassResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchUsers", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.UsersAjax.SearchUsersRequestBody Body;
        
        public SearchUsersRequest() {
        }
        
        public SearchUsersRequest(MgooGps.UsersAjax.SearchUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchUsersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UserName;
        
        public SearchUsersRequestBody() {
        }
        
        public SearchUsersRequestBody(int UserID, string UserName) {
            this.UserID = UserID;
            this.UserName = UserName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchUsersResponse", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.UsersAjax.SearchUsersResponseBody Body;
        
        public SearchUsersResponse() {
        }
        
        public SearchUsersResponse(MgooGps.UsersAjax.SearchUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SearchUsersResult;
        
        public SearchUsersResponseBody() {
        }
        
        public SearchUsersResponseBody(string SearchUsersResult) {
            this.SearchUsersResult = SearchUsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersRelationByDeviceIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsersRelationByDeviceID", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.UsersAjax.GetUsersRelationByDeviceIDRequestBody Body;
        
        public GetUsersRelationByDeviceIDRequest() {
        }
        
        public GetUsersRelationByDeviceIDRequest(MgooGps.UsersAjax.GetUsersRelationByDeviceIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUsersRelationByDeviceIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DeviceID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int UserID;
        
        public GetUsersRelationByDeviceIDRequestBody() {
        }
        
        public GetUsersRelationByDeviceIDRequestBody(int DeviceID, int UserID) {
            this.DeviceID = DeviceID;
            this.UserID = UserID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsersRelationByDeviceIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsersRelationByDeviceIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.UsersAjax.GetUsersRelationByDeviceIDResponseBody Body;
        
        public GetUsersRelationByDeviceIDResponse() {
        }
        
        public GetUsersRelationByDeviceIDResponse(MgooGps.UsersAjax.GetUsersRelationByDeviceIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUsersRelationByDeviceIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUsersRelationByDeviceIDResult;
        
        public GetUsersRelationByDeviceIDResponseBody() {
        }
        
        public GetUsersRelationByDeviceIDResponseBody(string GetUsersRelationByDeviceIDResult) {
            this.GetUsersRelationByDeviceIDResult = GetUsersRelationByDeviceIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserNameByLoginNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserNameByLoginName", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.UsersAjax.GetUserNameByLoginNameRequestBody Body;
        
        public GetUserNameByLoginNameRequest() {
        }
        
        public GetUserNameByLoginNameRequest(MgooGps.UsersAjax.GetUserNameByLoginNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserNameByLoginNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginName;
        
        public GetUserNameByLoginNameRequestBody() {
        }
        
        public GetUserNameByLoginNameRequestBody(string LoginName) {
            this.LoginName = LoginName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserNameByLoginNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserNameByLoginNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.UsersAjax.GetUserNameByLoginNameResponseBody Body;
        
        public GetUserNameByLoginNameResponse() {
        }
        
        public GetUserNameByLoginNameResponse(MgooGps.UsersAjax.GetUserNameByLoginNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserNameByLoginNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUserNameByLoginNameResult;
        
        public GetUserNameByLoginNameResponseBody() {
        }
        
        public GetUserNameByLoginNameResponseBody(string GetUserNameByLoginNameResult) {
            this.GetUserNameByLoginNameResult = GetUserNameByLoginNameResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UsersAjaxSoapChannel : MgooGps.UsersAjax.UsersAjaxSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UsersAjaxSoapClient : System.ServiceModel.ClientBase<MgooGps.UsersAjax.UsersAjaxSoap>, MgooGps.UsersAjax.UsersAjaxSoap {
        
        public UsersAjaxSoapClient() {
        }
        
        public UsersAjaxSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UsersAjaxSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsersAjaxSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UsersAjaxSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MgooGps.UsersAjax.GetZtreeResponse MgooGps.UsersAjax.UsersAjaxSoap.GetZtree(MgooGps.UsersAjax.GetZtreeRequest request) {
            return base.Channel.GetZtree(request);
        }
        
        public string GetZtree(int userID) {
            MgooGps.UsersAjax.GetZtreeRequest inValue = new MgooGps.UsersAjax.GetZtreeRequest();
            inValue.Body = new MgooGps.UsersAjax.GetZtreeRequestBody();
            inValue.Body.userID = userID;
            MgooGps.UsersAjax.GetZtreeResponse retVal = ((MgooGps.UsersAjax.UsersAjaxSoap)(this)).GetZtree(inValue);
            return retVal.Body.GetZtreeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MgooGps.UsersAjax.ValidPasswordResponse MgooGps.UsersAjax.UsersAjaxSoap.ValidPassword(MgooGps.UsersAjax.ValidPasswordRequest request) {
            return base.Channel.ValidPassword(request);
        }
        
        public int ValidPassword(int UserID, string Pass) {
            MgooGps.UsersAjax.ValidPasswordRequest inValue = new MgooGps.UsersAjax.ValidPasswordRequest();
            inValue.Body = new MgooGps.UsersAjax.ValidPasswordRequestBody();
            inValue.Body.UserID = UserID;
            inValue.Body.Pass = Pass;
            MgooGps.UsersAjax.ValidPasswordResponse retVal = ((MgooGps.UsersAjax.UsersAjaxSoap)(this)).ValidPassword(inValue);
            return retVal.Body.ValidPasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MgooGps.UsersAjax.GetLowerUsersResponse MgooGps.UsersAjax.UsersAjaxSoap.GetLowerUsers(MgooGps.UsersAjax.GetLowerUsersRequest request) {
            return base.Channel.GetLowerUsers(request);
        }
        
        public string GetLowerUsers(int UserID, int PageNo, int PageCount) {
            MgooGps.UsersAjax.GetLowerUsersRequest inValue = new MgooGps.UsersAjax.GetLowerUsersRequest();
            inValue.Body = new MgooGps.UsersAjax.GetLowerUsersRequestBody();
            inValue.Body.UserID = UserID;
            inValue.Body.PageNo = PageNo;
            inValue.Body.PageCount = PageCount;
            MgooGps.UsersAjax.GetLowerUsersResponse retVal = ((MgooGps.UsersAjax.UsersAjaxSoap)(this)).GetLowerUsers(inValue);
            return retVal.Body.GetLowerUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MgooGps.UsersAjax.SaveUsersResponse MgooGps.UsersAjax.UsersAjaxSoap.SaveUsers(MgooGps.UsersAjax.SaveUsersRequest request) {
            return base.Channel.SaveUsers(request);
        }
        
        public int SaveUsers(int ParentID, string UserName, string LoginName, string Pass, int UserType, string FirstName, string CellPhone, string Address, int Status) {
            MgooGps.UsersAjax.SaveUsersRequest inValue = new MgooGps.UsersAjax.SaveUsersRequest();
            inValue.Body = new MgooGps.UsersAjax.SaveUsersRequestBody();
            inValue.Body.ParentID = ParentID;
            inValue.Body.UserName = UserName;
            inValue.Body.LoginName = LoginName;
            inValue.Body.Pass = Pass;
            inValue.Body.UserType = UserType;
            inValue.Body.FirstName = FirstName;
            inValue.Body.CellPhone = CellPhone;
            inValue.Body.Address = Address;
            inValue.Body.Status = Status;
            MgooGps.UsersAjax.SaveUsersResponse retVal = ((MgooGps.UsersAjax.UsersAjaxSoap)(this)).SaveUsers(inValue);
            return retVal.Body.SaveUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MgooGps.UsersAjax.UpdateUserResponse MgooGps.UsersAjax.UsersAjaxSoap.UpdateUser(MgooGps.UsersAjax.UpdateUserRequest request) {
            return base.Channel.UpdateUser(request);
        }
        
        public bool UpdateUser(int UserID, int UserType, string FirstName, string CellPhone, string Address) {
            MgooGps.UsersAjax.UpdateUserRequest inValue = new MgooGps.UsersAjax.UpdateUserRequest();
            inValue.Body = new MgooGps.UsersAjax.UpdateUserRequestBody();
            inValue.Body.UserID = UserID;
            inValue.Body.UserType = UserType;
            inValue.Body.FirstName = FirstName;
            inValue.Body.CellPhone = CellPhone;
            inValue.Body.Address = Address;
            MgooGps.UsersAjax.UpdateUserResponse retVal = ((MgooGps.UsersAjax.UsersAjaxSoap)(this)).UpdateUser(inValue);
            return retVal.Body.UpdateUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MgooGps.UsersAjax.UpdateUserInfoResponse MgooGps.UsersAjax.UsersAjaxSoap.UpdateUserInfo(MgooGps.UsersAjax.UpdateUserInfoRequest request) {
            return base.Channel.UpdateUserInfo(request);
        }
        
        public bool UpdateUserInfo(int UserID, string FirstName, string CellPhone, string Address, string TimeZone, string Email, int SendType) {
            MgooGps.UsersAjax.UpdateUserInfoRequest inValue = new MgooGps.UsersAjax.UpdateUserInfoRequest();
            inValue.Body = new MgooGps.UsersAjax.UpdateUserInfoRequestBody();
            inValue.Body.UserID = UserID;
            inValue.Body.FirstName = FirstName;
            inValue.Body.CellPhone = CellPhone;
            inValue.Body.Address = Address;
            inValue.Body.TimeZone = TimeZone;
            inValue.Body.Email = Email;
            inValue.Body.SendType = SendType;
            MgooGps.UsersAjax.UpdateUserInfoResponse retVal = ((MgooGps.UsersAjax.UsersAjaxSoap)(this)).UpdateUserInfo(inValue);
            return retVal.Body.UpdateUserInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MgooGps.UsersAjax.UpdateUserPassResponse MgooGps.UsersAjax.UsersAjaxSoap.UpdateUserPass(MgooGps.UsersAjax.UpdateUserPassRequest request) {
            return base.Channel.UpdateUserPass(request);
        }
        
        public int UpdateUserPass(int UserID, string OldPass, string NewPass) {
            MgooGps.UsersAjax.UpdateUserPassRequest inValue = new MgooGps.UsersAjax.UpdateUserPassRequest();
            inValue.Body = new MgooGps.UsersAjax.UpdateUserPassRequestBody();
            inValue.Body.UserID = UserID;
            inValue.Body.OldPass = OldPass;
            inValue.Body.NewPass = NewPass;
            MgooGps.UsersAjax.UpdateUserPassResponse retVal = ((MgooGps.UsersAjax.UsersAjaxSoap)(this)).UpdateUserPass(inValue);
            return retVal.Body.UpdateUserPassResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MgooGps.UsersAjax.SearchUsersResponse MgooGps.UsersAjax.UsersAjaxSoap.SearchUsers(MgooGps.UsersAjax.SearchUsersRequest request) {
            return base.Channel.SearchUsers(request);
        }
        
        public string SearchUsers(int UserID, string UserName) {
            MgooGps.UsersAjax.SearchUsersRequest inValue = new MgooGps.UsersAjax.SearchUsersRequest();
            inValue.Body = new MgooGps.UsersAjax.SearchUsersRequestBody();
            inValue.Body.UserID = UserID;
            inValue.Body.UserName = UserName;
            MgooGps.UsersAjax.SearchUsersResponse retVal = ((MgooGps.UsersAjax.UsersAjaxSoap)(this)).SearchUsers(inValue);
            return retVal.Body.SearchUsersResult;
        }
        
        public int DelUserById(int UserID) {
            return base.Channel.DelUserById(UserID);
        }
        
        public int InitUserPassword(int UserID) {
            return base.Channel.InitUserPassword(UserID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MgooGps.UsersAjax.GetUsersRelationByDeviceIDResponse MgooGps.UsersAjax.UsersAjaxSoap.GetUsersRelationByDeviceID(MgooGps.UsersAjax.GetUsersRelationByDeviceIDRequest request) {
            return base.Channel.GetUsersRelationByDeviceID(request);
        }
        
        public string GetUsersRelationByDeviceID(int DeviceID, int UserID) {
            MgooGps.UsersAjax.GetUsersRelationByDeviceIDRequest inValue = new MgooGps.UsersAjax.GetUsersRelationByDeviceIDRequest();
            inValue.Body = new MgooGps.UsersAjax.GetUsersRelationByDeviceIDRequestBody();
            inValue.Body.DeviceID = DeviceID;
            inValue.Body.UserID = UserID;
            MgooGps.UsersAjax.GetUsersRelationByDeviceIDResponse retVal = ((MgooGps.UsersAjax.UsersAjaxSoap)(this)).GetUsersRelationByDeviceID(inValue);
            return retVal.Body.GetUsersRelationByDeviceIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MgooGps.UsersAjax.GetUserNameByLoginNameResponse MgooGps.UsersAjax.UsersAjaxSoap.GetUserNameByLoginName(MgooGps.UsersAjax.GetUserNameByLoginNameRequest request) {
            return base.Channel.GetUserNameByLoginName(request);
        }
        
        public string GetUserNameByLoginName(string LoginName) {
            MgooGps.UsersAjax.GetUserNameByLoginNameRequest inValue = new MgooGps.UsersAjax.GetUserNameByLoginNameRequest();
            inValue.Body = new MgooGps.UsersAjax.GetUserNameByLoginNameRequestBody();
            inValue.Body.LoginName = LoginName;
            MgooGps.UsersAjax.GetUserNameByLoginNameResponse retVal = ((MgooGps.UsersAjax.UsersAjaxSoap)(this)).GetUserNameByLoginName(inValue);
            return retVal.Body.GetUserNameByLoginNameResult;
        }
    }
}
