//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MgooGps.Geofence {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Geofence.GeofenceAjaxSoap")]
    public interface GeofenceAjaxSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GeofenceName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveGeofence", ReplyAction="*")]
        MgooGps.Geofence.SaveGeofenceResponse SaveGeofence(MgooGps.Geofence.SaveGeofenceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelGeofence", ReplyAction="*")]
        int DelGeofence(int GeofenceID, int DeviceID);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 TimeZone 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGeofence", ReplyAction="*")]
        MgooGps.Geofence.GetGeofenceResponse GetGeofence(MgooGps.Geofence.GetGeofenceRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 POIName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SavePOI", ReplyAction="*")]
        MgooGps.Geofence.SavePOIResponse SavePOI(MgooGps.Geofence.SavePOIRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 TimeZone 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPOI", ReplyAction="*")]
        MgooGps.Geofence.GetPOIResponse GetPOI(MgooGps.Geofence.GetPOIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelPOI", ReplyAction="*")]
        int DelPOI(int POIID);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 Name 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SavePolygon", ReplyAction="*")]
        MgooGps.Geofence.SavePolygonResponse SavePolygon(MgooGps.Geofence.SavePolygonRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 TimeZone 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPolygonList", ReplyAction="*")]
        MgooGps.Geofence.GetPolygonListResponse GetPolygonList(MgooGps.Geofence.GetPolygonListRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetPolygonDetailResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPolygonDetail", ReplyAction="*")]
        MgooGps.Geofence.GetPolygonDetailResponse GetPolygonDetail(MgooGps.Geofence.GetPolygonDetailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelPolygon", ReplyAction="*")]
        int DelPolygon(int ZoneID);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveGeofenceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveGeofence", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.Geofence.SaveGeofenceRequestBody Body;
        
        public SaveGeofenceRequest() {
        }
        
        public SaveGeofenceRequest(MgooGps.Geofence.SaveGeofenceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveGeofenceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int DeviceID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string GeofenceName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Remark;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public decimal Lat;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public decimal Lng;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public decimal Radius;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int GeofenceID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int TypeID;
        
        public SaveGeofenceRequestBody() {
        }
        
        public SaveGeofenceRequestBody(int UserID, int DeviceID, string GeofenceName, string Remark, decimal Lat, decimal Lng, decimal Radius, int GeofenceID, int TypeID) {
            this.UserID = UserID;
            this.DeviceID = DeviceID;
            this.GeofenceName = GeofenceName;
            this.Remark = Remark;
            this.Lat = Lat;
            this.Lng = Lng;
            this.Radius = Radius;
            this.GeofenceID = GeofenceID;
            this.TypeID = TypeID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveGeofenceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveGeofenceResponse", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.Geofence.SaveGeofenceResponseBody Body;
        
        public SaveGeofenceResponse() {
        }
        
        public SaveGeofenceResponse(MgooGps.Geofence.SaveGeofenceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveGeofenceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SaveGeofenceResult;
        
        public SaveGeofenceResponseBody() {
        }
        
        public SaveGeofenceResponseBody(int SaveGeofenceResult) {
            this.SaveGeofenceResult = SaveGeofenceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGeofenceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGeofence", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.Geofence.GetGeofenceRequestBody Body;
        
        public GetGeofenceRequest() {
        }
        
        public GetGeofenceRequest(MgooGps.Geofence.GetGeofenceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGeofenceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DeviceID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TimeZone;
        
        public GetGeofenceRequestBody() {
        }
        
        public GetGeofenceRequestBody(int DeviceID, string TimeZone) {
            this.DeviceID = DeviceID;
            this.TimeZone = TimeZone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGeofenceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGeofenceResponse", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.Geofence.GetGeofenceResponseBody Body;
        
        public GetGeofenceResponse() {
        }
        
        public GetGeofenceResponse(MgooGps.Geofence.GetGeofenceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGeofenceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetGeofenceResult;
        
        public GetGeofenceResponseBody() {
        }
        
        public GetGeofenceResponseBody(string GetGeofenceResult) {
            this.GetGeofenceResult = GetGeofenceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SavePOIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SavePOI", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.Geofence.SavePOIRequestBody Body;
        
        public SavePOIRequest() {
        }
        
        public SavePOIRequest(MgooGps.Geofence.SavePOIRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SavePOIRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string POIName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal Lat;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal Lng;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int TypeID;
        
        public SavePOIRequestBody() {
        }
        
        public SavePOIRequestBody(int UserID, string POIName, decimal Lat, decimal Lng, int TypeID) {
            this.UserID = UserID;
            this.POIName = POIName;
            this.Lat = Lat;
            this.Lng = Lng;
            this.TypeID = TypeID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SavePOIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SavePOIResponse", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.Geofence.SavePOIResponseBody Body;
        
        public SavePOIResponse() {
        }
        
        public SavePOIResponse(MgooGps.Geofence.SavePOIResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SavePOIResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SavePOIResult;
        
        public SavePOIResponseBody() {
        }
        
        public SavePOIResponseBody(int SavePOIResult) {
            this.SavePOIResult = SavePOIResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPOIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPOI", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.Geofence.GetPOIRequestBody Body;
        
        public GetPOIRequest() {
        }
        
        public GetPOIRequest(MgooGps.Geofence.GetPOIRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPOIRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TimeZone;
        
        public GetPOIRequestBody() {
        }
        
        public GetPOIRequestBody(int UserID, string TimeZone) {
            this.UserID = UserID;
            this.TimeZone = TimeZone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPOIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPOIResponse", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.Geofence.GetPOIResponseBody Body;
        
        public GetPOIResponse() {
        }
        
        public GetPOIResponse(MgooGps.Geofence.GetPOIResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPOIResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetPOIResult;
        
        public GetPOIResponseBody() {
        }
        
        public GetPOIResponseBody(string GetPOIResult) {
            this.GetPOIResult = GetPOIResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SavePolygonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SavePolygon", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.Geofence.SavePolygonRequestBody Body;
        
        public SavePolygonRequest() {
        }
        
        public SavePolygonRequest(MgooGps.Geofence.SavePolygonRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SavePolygonRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int ZoneID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string LatLngs;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string DeviceIDs;
        
        public SavePolygonRequestBody() {
        }
        
        public SavePolygonRequestBody(int UserID, int ZoneID, string Name, string LatLngs, string DeviceIDs) {
            this.UserID = UserID;
            this.ZoneID = ZoneID;
            this.Name = Name;
            this.LatLngs = LatLngs;
            this.DeviceIDs = DeviceIDs;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SavePolygonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SavePolygonResponse", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.Geofence.SavePolygonResponseBody Body;
        
        public SavePolygonResponse() {
        }
        
        public SavePolygonResponse(MgooGps.Geofence.SavePolygonResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SavePolygonResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SavePolygonResult;
        
        public SavePolygonResponseBody() {
        }
        
        public SavePolygonResponseBody(int SavePolygonResult) {
            this.SavePolygonResult = SavePolygonResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPolygonListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPolygonList", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.Geofence.GetPolygonListRequestBody Body;
        
        public GetPolygonListRequest() {
        }
        
        public GetPolygonListRequest(MgooGps.Geofence.GetPolygonListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPolygonListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TimeZone;
        
        public GetPolygonListRequestBody() {
        }
        
        public GetPolygonListRequestBody(int UserID, string TimeZone) {
            this.UserID = UserID;
            this.TimeZone = TimeZone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPolygonListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPolygonListResponse", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.Geofence.GetPolygonListResponseBody Body;
        
        public GetPolygonListResponse() {
        }
        
        public GetPolygonListResponse(MgooGps.Geofence.GetPolygonListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPolygonListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetPolygonListResult;
        
        public GetPolygonListResponseBody() {
        }
        
        public GetPolygonListResponseBody(string GetPolygonListResult) {
            this.GetPolygonListResult = GetPolygonListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPolygonDetailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPolygonDetail", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.Geofence.GetPolygonDetailRequestBody Body;
        
        public GetPolygonDetailRequest() {
        }
        
        public GetPolygonDetailRequest(MgooGps.Geofence.GetPolygonDetailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPolygonDetailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ZoneID;
        
        public GetPolygonDetailRequestBody() {
        }
        
        public GetPolygonDetailRequestBody(int ZoneID) {
            this.ZoneID = ZoneID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPolygonDetailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPolygonDetailResponse", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.Geofence.GetPolygonDetailResponseBody Body;
        
        public GetPolygonDetailResponse() {
        }
        
        public GetPolygonDetailResponse(MgooGps.Geofence.GetPolygonDetailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPolygonDetailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetPolygonDetailResult;
        
        public GetPolygonDetailResponseBody() {
        }
        
        public GetPolygonDetailResponseBody(string GetPolygonDetailResult) {
            this.GetPolygonDetailResult = GetPolygonDetailResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GeofenceAjaxSoapChannel : MgooGps.Geofence.GeofenceAjaxSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GeofenceAjaxSoapClient : System.ServiceModel.ClientBase<MgooGps.Geofence.GeofenceAjaxSoap>, MgooGps.Geofence.GeofenceAjaxSoap {
        
        public GeofenceAjaxSoapClient() {
        }
        
        public GeofenceAjaxSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GeofenceAjaxSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeofenceAjaxSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeofenceAjaxSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MgooGps.Geofence.SaveGeofenceResponse MgooGps.Geofence.GeofenceAjaxSoap.SaveGeofence(MgooGps.Geofence.SaveGeofenceRequest request) {
            return base.Channel.SaveGeofence(request);
        }
        
        public int SaveGeofence(int UserID, int DeviceID, string GeofenceName, string Remark, decimal Lat, decimal Lng, decimal Radius, int GeofenceID, int TypeID) {
            MgooGps.Geofence.SaveGeofenceRequest inValue = new MgooGps.Geofence.SaveGeofenceRequest();
            inValue.Body = new MgooGps.Geofence.SaveGeofenceRequestBody();
            inValue.Body.UserID = UserID;
            inValue.Body.DeviceID = DeviceID;
            inValue.Body.GeofenceName = GeofenceName;
            inValue.Body.Remark = Remark;
            inValue.Body.Lat = Lat;
            inValue.Body.Lng = Lng;
            inValue.Body.Radius = Radius;
            inValue.Body.GeofenceID = GeofenceID;
            inValue.Body.TypeID = TypeID;
            MgooGps.Geofence.SaveGeofenceResponse retVal = ((MgooGps.Geofence.GeofenceAjaxSoap)(this)).SaveGeofence(inValue);
            return retVal.Body.SaveGeofenceResult;
        }
        
        public int DelGeofence(int GeofenceID, int DeviceID) {
            return base.Channel.DelGeofence(GeofenceID, DeviceID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MgooGps.Geofence.GetGeofenceResponse MgooGps.Geofence.GeofenceAjaxSoap.GetGeofence(MgooGps.Geofence.GetGeofenceRequest request) {
            return base.Channel.GetGeofence(request);
        }
        
        public string GetGeofence(int DeviceID, string TimeZone) {
            MgooGps.Geofence.GetGeofenceRequest inValue = new MgooGps.Geofence.GetGeofenceRequest();
            inValue.Body = new MgooGps.Geofence.GetGeofenceRequestBody();
            inValue.Body.DeviceID = DeviceID;
            inValue.Body.TimeZone = TimeZone;
            MgooGps.Geofence.GetGeofenceResponse retVal = ((MgooGps.Geofence.GeofenceAjaxSoap)(this)).GetGeofence(inValue);
            return retVal.Body.GetGeofenceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MgooGps.Geofence.SavePOIResponse MgooGps.Geofence.GeofenceAjaxSoap.SavePOI(MgooGps.Geofence.SavePOIRequest request) {
            return base.Channel.SavePOI(request);
        }
        
        public int SavePOI(int UserID, string POIName, decimal Lat, decimal Lng, int TypeID) {
            MgooGps.Geofence.SavePOIRequest inValue = new MgooGps.Geofence.SavePOIRequest();
            inValue.Body = new MgooGps.Geofence.SavePOIRequestBody();
            inValue.Body.UserID = UserID;
            inValue.Body.POIName = POIName;
            inValue.Body.Lat = Lat;
            inValue.Body.Lng = Lng;
            inValue.Body.TypeID = TypeID;
            MgooGps.Geofence.SavePOIResponse retVal = ((MgooGps.Geofence.GeofenceAjaxSoap)(this)).SavePOI(inValue);
            return retVal.Body.SavePOIResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MgooGps.Geofence.GetPOIResponse MgooGps.Geofence.GeofenceAjaxSoap.GetPOI(MgooGps.Geofence.GetPOIRequest request) {
            return base.Channel.GetPOI(request);
        }
        
        public string GetPOI(int UserID, string TimeZone) {
            MgooGps.Geofence.GetPOIRequest inValue = new MgooGps.Geofence.GetPOIRequest();
            inValue.Body = new MgooGps.Geofence.GetPOIRequestBody();
            inValue.Body.UserID = UserID;
            inValue.Body.TimeZone = TimeZone;
            MgooGps.Geofence.GetPOIResponse retVal = ((MgooGps.Geofence.GeofenceAjaxSoap)(this)).GetPOI(inValue);
            return retVal.Body.GetPOIResult;
        }
        
        public int DelPOI(int POIID) {
            return base.Channel.DelPOI(POIID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MgooGps.Geofence.SavePolygonResponse MgooGps.Geofence.GeofenceAjaxSoap.SavePolygon(MgooGps.Geofence.SavePolygonRequest request) {
            return base.Channel.SavePolygon(request);
        }
        
        public int SavePolygon(int UserID, int ZoneID, string Name, string LatLngs, string DeviceIDs) {
            MgooGps.Geofence.SavePolygonRequest inValue = new MgooGps.Geofence.SavePolygonRequest();
            inValue.Body = new MgooGps.Geofence.SavePolygonRequestBody();
            inValue.Body.UserID = UserID;
            inValue.Body.ZoneID = ZoneID;
            inValue.Body.Name = Name;
            inValue.Body.LatLngs = LatLngs;
            inValue.Body.DeviceIDs = DeviceIDs;
            MgooGps.Geofence.SavePolygonResponse retVal = ((MgooGps.Geofence.GeofenceAjaxSoap)(this)).SavePolygon(inValue);
            return retVal.Body.SavePolygonResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MgooGps.Geofence.GetPolygonListResponse MgooGps.Geofence.GeofenceAjaxSoap.GetPolygonList(MgooGps.Geofence.GetPolygonListRequest request) {
            return base.Channel.GetPolygonList(request);
        }
        
        public string GetPolygonList(int UserID, string TimeZone) {
            MgooGps.Geofence.GetPolygonListRequest inValue = new MgooGps.Geofence.GetPolygonListRequest();
            inValue.Body = new MgooGps.Geofence.GetPolygonListRequestBody();
            inValue.Body.UserID = UserID;
            inValue.Body.TimeZone = TimeZone;
            MgooGps.Geofence.GetPolygonListResponse retVal = ((MgooGps.Geofence.GeofenceAjaxSoap)(this)).GetPolygonList(inValue);
            return retVal.Body.GetPolygonListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MgooGps.Geofence.GetPolygonDetailResponse MgooGps.Geofence.GeofenceAjaxSoap.GetPolygonDetail(MgooGps.Geofence.GetPolygonDetailRequest request) {
            return base.Channel.GetPolygonDetail(request);
        }
        
        public string GetPolygonDetail(int ZoneID) {
            MgooGps.Geofence.GetPolygonDetailRequest inValue = new MgooGps.Geofence.GetPolygonDetailRequest();
            inValue.Body = new MgooGps.Geofence.GetPolygonDetailRequestBody();
            inValue.Body.ZoneID = ZoneID;
            MgooGps.Geofence.GetPolygonDetailResponse retVal = ((MgooGps.Geofence.GeofenceAjaxSoap)(this)).GetPolygonDetail(inValue);
            return retVal.Body.GetPolygonDetailResult;
        }
        
        public int DelPolygon(int ZoneID) {
            return base.Channel.DelPolygon(ZoneID);
        }
    }
}
