//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MgooGps.DevicesAjax {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DevicesAjax.DevicesAjaxSoap")]
    public interface DevicesAjaxSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 IMEIs 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveDevices", ReplyAction="*")]
        MgooGps.DevicesAjax.SaveDevicesResponse SaveDevices(MgooGps.DevicesAjax.SaveDevicesRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 SN 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDevices", ReplyAction="*")]
        MgooGps.DevicesAjax.GetDevicesResponse GetDevices(MgooGps.DevicesAjax.GetDevicesRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 TimeZones 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDevicesByUserID", ReplyAction="*")]
        MgooGps.DevicesAjax.GetDevicesByUserIDResponse GetDevicesByUserID(MgooGps.DevicesAjax.GetDevicesByUserIDRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 TimeZones 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGeofenceDevicesByUserID", ReplyAction="*")]
        MgooGps.DevicesAjax.GetGeofenceDevicesByUserIDResponse GetGeofenceDevicesByUserID(MgooGps.DevicesAjax.GetGeofenceDevicesByUserIDRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 GetDeviceCountResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDeviceCount", ReplyAction="*")]
        MgooGps.DevicesAjax.GetDeviceCountResponse GetDeviceCount(MgooGps.DevicesAjax.GetDeviceCountRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 SN 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetExpireDevices", ReplyAction="*")]
        MgooGps.DevicesAjax.GetExpireDevicesResponse GetExpireDevices(MgooGps.DevicesAjax.GetExpireDevicesRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 DeviceIDs 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaleDevices", ReplyAction="*")]
        MgooGps.DevicesAjax.SaleDevicesResponse SaleDevices(MgooGps.DevicesAjax.SaleDevicesRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 SNName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SearchDevices", ReplyAction="*")]
        MgooGps.DevicesAjax.SearchDevicesResponse SearchDevices(MgooGps.DevicesAjax.SearchDevicesRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 TimeZone 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDevicesHistory", ReplyAction="*")]
        MgooGps.DevicesAjax.GetDevicesHistoryResponse GetDevicesHistory(MgooGps.DevicesAjax.GetDevicesHistoryRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 StartTime 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDeviceHistoryByRoadOffset", ReplyAction="*")]
        MgooGps.DevicesAjax.GetDeviceHistoryByRoadOffsetResponse GetDeviceHistoryByRoadOffset(MgooGps.DevicesAjax.GetDeviceHistoryByRoadOffsetRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 TimeZone 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTracking", ReplyAction="*")]
        MgooGps.DevicesAjax.GetTrackingResponse GetTracking(MgooGps.DevicesAjax.GetTrackingRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 DeviceIDs 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateHireExpriDate", ReplyAction="*")]
        MgooGps.DevicesAjax.UpdateHireExpriDateResponse UpdateHireExpriDate(MgooGps.DevicesAjax.UpdateHireExpriDateRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 DeviceIDs 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateHireExpriDateDays", ReplyAction="*")]
        MgooGps.DevicesAjax.UpdateHireExpriDateDaysResponse UpdateHireExpriDateDays(MgooGps.DevicesAjax.UpdateHireExpriDateDaysRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 DeviceIDs 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangeDevicesUser", ReplyAction="*")]
        MgooGps.DevicesAjax.ChangeDevicesUserResponse ChangeDevicesUser(MgooGps.DevicesAjax.ChangeDevicesUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DelDevice", ReplyAction="*")]
        int DelDevice(int DeviceID);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 OldPass 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangeDevicePassword", ReplyAction="*")]
        MgooGps.DevicesAjax.ChangeDevicePasswordResponse ChangeDevicePassword(MgooGps.DevicesAjax.ChangeDevicePasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InitDevicePassword", ReplyAction="*")]
        int InitDevicePassword(int DeviceID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDeviceGroupID", ReplyAction="*")]
        int UpdateDeviceGroupID(int DeviceID, int GroupID);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveDevicesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveDevices", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.DevicesAjax.SaveDevicesRequestBody Body;
        
        public SaveDevicesRequest() {
        }
        
        public SaveDevicesRequest(MgooGps.DevicesAjax.SaveDevicesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveDevicesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int CategoryID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string IMEIs;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string OverSpeed;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int IsImeis;
        
        public SaveDevicesRequestBody() {
        }
        
        public SaveDevicesRequestBody(int UserID, int CategoryID, string IMEIs, string OverSpeed, int IsImeis) {
            this.UserID = UserID;
            this.CategoryID = CategoryID;
            this.IMEIs = IMEIs;
            this.OverSpeed = OverSpeed;
            this.IsImeis = IsImeis;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveDevicesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveDevicesResponse", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.DevicesAjax.SaveDevicesResponseBody Body;
        
        public SaveDevicesResponse() {
        }
        
        public SaveDevicesResponse(MgooGps.DevicesAjax.SaveDevicesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveDevicesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SaveDevicesResult;
        
        public SaveDevicesResponseBody() {
        }
        
        public SaveDevicesResponseBody(string SaveDevicesResult) {
            this.SaveDevicesResult = SaveDevicesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDevicesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDevices", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.DevicesAjax.GetDevicesRequestBody Body;
        
        public GetDevicesRequest() {
        }
        
        public GetDevicesRequest(MgooGps.DevicesAjax.GetDevicesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDevicesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int PageNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int PageCount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string SN;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string TimeZones;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int ExpDays;
        
        public GetDevicesRequestBody() {
        }
        
        public GetDevicesRequestBody(int UserID, int PageNo, int PageCount, string SN, string TimeZones, int ExpDays) {
            this.UserID = UserID;
            this.PageNo = PageNo;
            this.PageCount = PageCount;
            this.SN = SN;
            this.TimeZones = TimeZones;
            this.ExpDays = ExpDays;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDevicesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDevicesResponse", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.DevicesAjax.GetDevicesResponseBody Body;
        
        public GetDevicesResponse() {
        }
        
        public GetDevicesResponse(MgooGps.DevicesAjax.GetDevicesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDevicesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDevicesResult;
        
        public GetDevicesResponseBody() {
        }
        
        public GetDevicesResponseBody(string GetDevicesResult) {
            this.GetDevicesResult = GetDevicesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDevicesByUserIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDevicesByUserID", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.DevicesAjax.GetDevicesByUserIDRequestBody Body;
        
        public GetDevicesByUserIDRequest() {
        }
        
        public GetDevicesByUserIDRequest(MgooGps.DevicesAjax.GetDevicesByUserIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDevicesByUserIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool isFirst;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TimeZones;
        
        public GetDevicesByUserIDRequestBody() {
        }
        
        public GetDevicesByUserIDRequestBody(int UserID, bool isFirst, string TimeZones) {
            this.UserID = UserID;
            this.isFirst = isFirst;
            this.TimeZones = TimeZones;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDevicesByUserIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDevicesByUserIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.DevicesAjax.GetDevicesByUserIDResponseBody Body;
        
        public GetDevicesByUserIDResponse() {
        }
        
        public GetDevicesByUserIDResponse(MgooGps.DevicesAjax.GetDevicesByUserIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDevicesByUserIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDevicesByUserIDResult;
        
        public GetDevicesByUserIDResponseBody() {
        }
        
        public GetDevicesByUserIDResponseBody(string GetDevicesByUserIDResult) {
            this.GetDevicesByUserIDResult = GetDevicesByUserIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGeofenceDevicesByUserIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGeofenceDevicesByUserID", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.DevicesAjax.GetGeofenceDevicesByUserIDRequestBody Body;
        
        public GetGeofenceDevicesByUserIDRequest() {
        }
        
        public GetGeofenceDevicesByUserIDRequest(MgooGps.DevicesAjax.GetGeofenceDevicesByUserIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGeofenceDevicesByUserIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool isFirst;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TimeZones;
        
        public GetGeofenceDevicesByUserIDRequestBody() {
        }
        
        public GetGeofenceDevicesByUserIDRequestBody(int UserID, bool isFirst, string TimeZones) {
            this.UserID = UserID;
            this.isFirst = isFirst;
            this.TimeZones = TimeZones;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGeofenceDevicesByUserIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGeofenceDevicesByUserIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.DevicesAjax.GetGeofenceDevicesByUserIDResponseBody Body;
        
        public GetGeofenceDevicesByUserIDResponse() {
        }
        
        public GetGeofenceDevicesByUserIDResponse(MgooGps.DevicesAjax.GetGeofenceDevicesByUserIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGeofenceDevicesByUserIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetGeofenceDevicesByUserIDResult;
        
        public GetGeofenceDevicesByUserIDResponseBody() {
        }
        
        public GetGeofenceDevicesByUserIDResponseBody(string GetGeofenceDevicesByUserIDResult) {
            this.GetGeofenceDevicesByUserIDResult = GetGeofenceDevicesByUserIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDeviceCountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDeviceCount", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.DevicesAjax.GetDeviceCountRequestBody Body;
        
        public GetDeviceCountRequest() {
        }
        
        public GetDeviceCountRequest(MgooGps.DevicesAjax.GetDeviceCountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDeviceCountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UserID;
        
        public GetDeviceCountRequestBody() {
        }
        
        public GetDeviceCountRequestBody(int UserID) {
            this.UserID = UserID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDeviceCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDeviceCountResponse", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.DevicesAjax.GetDeviceCountResponseBody Body;
        
        public GetDeviceCountResponse() {
        }
        
        public GetDeviceCountResponse(MgooGps.DevicesAjax.GetDeviceCountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDeviceCountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDeviceCountResult;
        
        public GetDeviceCountResponseBody() {
        }
        
        public GetDeviceCountResponseBody(string GetDeviceCountResult) {
            this.GetDeviceCountResult = GetDeviceCountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExpireDevicesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExpireDevices", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.DevicesAjax.GetExpireDevicesRequestBody Body;
        
        public GetExpireDevicesRequest() {
        }
        
        public GetExpireDevicesRequest(MgooGps.DevicesAjax.GetExpireDevicesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetExpireDevicesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SN;
        
        public GetExpireDevicesRequestBody() {
        }
        
        public GetExpireDevicesRequestBody(int UserID, string SN) {
            this.UserID = UserID;
            this.SN = SN;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetExpireDevicesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetExpireDevicesResponse", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.DevicesAjax.GetExpireDevicesResponseBody Body;
        
        public GetExpireDevicesResponse() {
        }
        
        public GetExpireDevicesResponse(MgooGps.DevicesAjax.GetExpireDevicesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetExpireDevicesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetExpireDevicesResult;
        
        public GetExpireDevicesResponseBody() {
        }
        
        public GetExpireDevicesResponseBody(string GetExpireDevicesResult) {
            this.GetExpireDevicesResult = GetExpireDevicesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaleDevicesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaleDevices", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.DevicesAjax.SaleDevicesRequestBody Body;
        
        public SaleDevicesRequest() {
        }
        
        public SaleDevicesRequest(MgooGps.DevicesAjax.SaleDevicesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaleDevicesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int SaleUserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int UserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string DeviceIDs;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ExpireDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PhoneNum;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int isMany;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Remark;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string TimeZones;
        
        public SaleDevicesRequestBody() {
        }
        
        public SaleDevicesRequestBody(int SaleUserID, int UserID, string DeviceIDs, string ExpireDate, string PhoneNum, int isMany, string Remark, string TimeZones) {
            this.SaleUserID = SaleUserID;
            this.UserID = UserID;
            this.DeviceIDs = DeviceIDs;
            this.ExpireDate = ExpireDate;
            this.PhoneNum = PhoneNum;
            this.isMany = isMany;
            this.Remark = Remark;
            this.TimeZones = TimeZones;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaleDevicesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaleDevicesResponse", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.DevicesAjax.SaleDevicesResponseBody Body;
        
        public SaleDevicesResponse() {
        }
        
        public SaleDevicesResponse(MgooGps.DevicesAjax.SaleDevicesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaleDevicesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SaleDevicesResult;
        
        public SaleDevicesResponseBody() {
        }
        
        public SaleDevicesResponseBody(string SaleDevicesResult) {
            this.SaleDevicesResult = SaleDevicesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchDevicesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchDevices", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.DevicesAjax.SearchDevicesRequestBody Body;
        
        public SearchDevicesRequest() {
        }
        
        public SearchDevicesRequest(MgooGps.DevicesAjax.SearchDevicesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchDevicesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SNName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int SNTypeID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int OfflineType;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int TimeTypeID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string StartTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string EndTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string TimeZones;
        
        public SearchDevicesRequestBody() {
        }
        
        public SearchDevicesRequestBody(int UserID, string SNName, int SNTypeID, int OfflineType, int TimeTypeID, string StartTime, string EndTime, string TimeZones) {
            this.UserID = UserID;
            this.SNName = SNName;
            this.SNTypeID = SNTypeID;
            this.OfflineType = OfflineType;
            this.TimeTypeID = TimeTypeID;
            this.StartTime = StartTime;
            this.EndTime = EndTime;
            this.TimeZones = TimeZones;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SearchDevicesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchDevicesResponse", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.DevicesAjax.SearchDevicesResponseBody Body;
        
        public SearchDevicesResponse() {
        }
        
        public SearchDevicesResponse(MgooGps.DevicesAjax.SearchDevicesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SearchDevicesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SearchDevicesResult;
        
        public SearchDevicesResponseBody() {
        }
        
        public SearchDevicesResponseBody(string SearchDevicesResult) {
            this.SearchDevicesResult = SearchDevicesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDevicesHistoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDevicesHistory", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.DevicesAjax.GetDevicesHistoryRequestBody Body;
        
        public GetDevicesHistoryRequest() {
        }
        
        public GetDevicesHistoryRequest(MgooGps.DevicesAjax.GetDevicesHistoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDevicesHistoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DeviceID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime Start;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime End;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TimeZone;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int ShowLBS;
        
        public GetDevicesHistoryRequestBody() {
        }
        
        public GetDevicesHistoryRequestBody(int DeviceID, System.DateTime Start, System.DateTime End, string TimeZone, int ShowLBS) {
            this.DeviceID = DeviceID;
            this.Start = Start;
            this.End = End;
            this.TimeZone = TimeZone;
            this.ShowLBS = ShowLBS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDevicesHistoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDevicesHistoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.DevicesAjax.GetDevicesHistoryResponseBody Body;
        
        public GetDevicesHistoryResponse() {
        }
        
        public GetDevicesHistoryResponse(MgooGps.DevicesAjax.GetDevicesHistoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDevicesHistoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDevicesHistoryResult;
        
        public GetDevicesHistoryResponseBody() {
        }
        
        public GetDevicesHistoryResponseBody(string GetDevicesHistoryResult) {
            this.GetDevicesHistoryResult = GetDevicesHistoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDeviceHistoryByRoadOffsetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDeviceHistoryByRoadOffset", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.DevicesAjax.GetDeviceHistoryByRoadOffsetRequestBody Body;
        
        public GetDeviceHistoryByRoadOffsetRequest() {
        }
        
        public GetDeviceHistoryByRoadOffsetRequest(MgooGps.DevicesAjax.GetDeviceHistoryByRoadOffsetRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDeviceHistoryByRoadOffsetRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DeviceID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string StartTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string EndTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TimeZone;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int ShowLBS;
        
        public GetDeviceHistoryByRoadOffsetRequestBody() {
        }
        
        public GetDeviceHistoryByRoadOffsetRequestBody(int DeviceID, string StartTime, string EndTime, string TimeZone, int ShowLBS) {
            this.DeviceID = DeviceID;
            this.StartTime = StartTime;
            this.EndTime = EndTime;
            this.TimeZone = TimeZone;
            this.ShowLBS = ShowLBS;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDeviceHistoryByRoadOffsetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDeviceHistoryByRoadOffsetResponse", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.DevicesAjax.GetDeviceHistoryByRoadOffsetResponseBody Body;
        
        public GetDeviceHistoryByRoadOffsetResponse() {
        }
        
        public GetDeviceHistoryByRoadOffsetResponse(MgooGps.DevicesAjax.GetDeviceHistoryByRoadOffsetResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDeviceHistoryByRoadOffsetResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDeviceHistoryByRoadOffsetResult;
        
        public GetDeviceHistoryByRoadOffsetResponseBody() {
        }
        
        public GetDeviceHistoryByRoadOffsetResponseBody(string GetDeviceHistoryByRoadOffsetResult) {
            this.GetDeviceHistoryByRoadOffsetResult = GetDeviceHistoryByRoadOffsetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTrackingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTracking", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.DevicesAjax.GetTrackingRequestBody Body;
        
        public GetTrackingRequest() {
        }
        
        public GetTrackingRequest(MgooGps.DevicesAjax.GetTrackingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTrackingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DeviceID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TimeZone;
        
        public GetTrackingRequestBody() {
        }
        
        public GetTrackingRequestBody(int DeviceID, string TimeZone) {
            this.DeviceID = DeviceID;
            this.TimeZone = TimeZone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTrackingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTrackingResponse", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.DevicesAjax.GetTrackingResponseBody Body;
        
        public GetTrackingResponse() {
        }
        
        public GetTrackingResponse(MgooGps.DevicesAjax.GetTrackingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTrackingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetTrackingResult;
        
        public GetTrackingResponseBody() {
        }
        
        public GetTrackingResponseBody(string GetTrackingResult) {
            this.GetTrackingResult = GetTrackingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateHireExpriDateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateHireExpriDate", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.DevicesAjax.UpdateHireExpriDateRequestBody Body;
        
        public UpdateHireExpriDateRequest() {
        }
        
        public UpdateHireExpriDateRequest(MgooGps.DevicesAjax.UpdateHireExpriDateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateHireExpriDateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeviceIDs;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string EndTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TimeZone;
        
        public UpdateHireExpriDateRequestBody() {
        }
        
        public UpdateHireExpriDateRequestBody(string DeviceIDs, string EndTime, string TimeZone) {
            this.DeviceIDs = DeviceIDs;
            this.EndTime = EndTime;
            this.TimeZone = TimeZone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateHireExpriDateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateHireExpriDateResponse", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.DevicesAjax.UpdateHireExpriDateResponseBody Body;
        
        public UpdateHireExpriDateResponse() {
        }
        
        public UpdateHireExpriDateResponse(MgooGps.DevicesAjax.UpdateHireExpriDateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateHireExpriDateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdateHireExpriDateResult;
        
        public UpdateHireExpriDateResponseBody() {
        }
        
        public UpdateHireExpriDateResponseBody(int UpdateHireExpriDateResult) {
            this.UpdateHireExpriDateResult = UpdateHireExpriDateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateHireExpriDateDaysRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateHireExpriDateDays", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.DevicesAjax.UpdateHireExpriDateDaysRequestBody Body;
        
        public UpdateHireExpriDateDaysRequest() {
        }
        
        public UpdateHireExpriDateDaysRequest(MgooGps.DevicesAjax.UpdateHireExpriDateDaysRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateHireExpriDateDaysRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DeviceIDs;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int AddHireDays;
        
        public UpdateHireExpriDateDaysRequestBody() {
        }
        
        public UpdateHireExpriDateDaysRequestBody(int UserID, string DeviceIDs, int AddHireDays) {
            this.UserID = UserID;
            this.DeviceIDs = DeviceIDs;
            this.AddHireDays = AddHireDays;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateHireExpriDateDaysResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateHireExpriDateDaysResponse", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.DevicesAjax.UpdateHireExpriDateDaysResponseBody Body;
        
        public UpdateHireExpriDateDaysResponse() {
        }
        
        public UpdateHireExpriDateDaysResponse(MgooGps.DevicesAjax.UpdateHireExpriDateDaysResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateHireExpriDateDaysResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdateHireExpriDateDaysResult;
        
        public UpdateHireExpriDateDaysResponseBody() {
        }
        
        public UpdateHireExpriDateDaysResponseBody(int UpdateHireExpriDateDaysResult) {
            this.UpdateHireExpriDateDaysResult = UpdateHireExpriDateDaysResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeDevicesUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeDevicesUser", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.DevicesAjax.ChangeDevicesUserRequestBody Body;
        
        public ChangeDevicesUserRequest() {
        }
        
        public ChangeDevicesUserRequest(MgooGps.DevicesAjax.ChangeDevicesUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangeDevicesUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeviceIDs;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int OldUserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int NewUserID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string TimeZone;
        
        public ChangeDevicesUserRequestBody() {
        }
        
        public ChangeDevicesUserRequestBody(string DeviceIDs, int OldUserID, int NewUserID, string TimeZone) {
            this.DeviceIDs = DeviceIDs;
            this.OldUserID = OldUserID;
            this.NewUserID = NewUserID;
            this.TimeZone = TimeZone;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeDevicesUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeDevicesUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.DevicesAjax.ChangeDevicesUserResponseBody Body;
        
        public ChangeDevicesUserResponse() {
        }
        
        public ChangeDevicesUserResponse(MgooGps.DevicesAjax.ChangeDevicesUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangeDevicesUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ChangeDevicesUserResult;
        
        public ChangeDevicesUserResponseBody() {
        }
        
        public ChangeDevicesUserResponseBody(int ChangeDevicesUserResult) {
            this.ChangeDevicesUserResult = ChangeDevicesUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeDevicePasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeDevicePassword", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.DevicesAjax.ChangeDevicePasswordRequestBody Body;
        
        public ChangeDevicePasswordRequest() {
        }
        
        public ChangeDevicePasswordRequest(MgooGps.DevicesAjax.ChangeDevicePasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangeDevicePasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DeviceID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string OldPass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string NewPass;
        
        public ChangeDevicePasswordRequestBody() {
        }
        
        public ChangeDevicePasswordRequestBody(int DeviceID, string OldPass, string NewPass) {
            this.DeviceID = DeviceID;
            this.OldPass = OldPass;
            this.NewPass = NewPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeDevicePasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeDevicePasswordResponse", Namespace="http://tempuri.org/", Order=0)]
        public MgooGps.DevicesAjax.ChangeDevicePasswordResponseBody Body;
        
        public ChangeDevicePasswordResponse() {
        }
        
        public ChangeDevicePasswordResponse(MgooGps.DevicesAjax.ChangeDevicePasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangeDevicePasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ChangeDevicePasswordResult;
        
        public ChangeDevicePasswordResponseBody() {
        }
        
        public ChangeDevicePasswordResponseBody(int ChangeDevicePasswordResult) {
            this.ChangeDevicePasswordResult = ChangeDevicePasswordResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DevicesAjaxSoapChannel : MgooGps.DevicesAjax.DevicesAjaxSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DevicesAjaxSoapClient : System.ServiceModel.ClientBase<MgooGps.DevicesAjax.DevicesAjaxSoap>, MgooGps.DevicesAjax.DevicesAjaxSoap {
        
        public DevicesAjaxSoapClient() {
        }
        
        public DevicesAjaxSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DevicesAjaxSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DevicesAjaxSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DevicesAjaxSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MgooGps.DevicesAjax.SaveDevicesResponse MgooGps.DevicesAjax.DevicesAjaxSoap.SaveDevices(MgooGps.DevicesAjax.SaveDevicesRequest request) {
            return base.Channel.SaveDevices(request);
        }
        
        public string SaveDevices(int UserID, int CategoryID, string IMEIs, string OverSpeed, int IsImeis) {
            MgooGps.DevicesAjax.SaveDevicesRequest inValue = new MgooGps.DevicesAjax.SaveDevicesRequest();
            inValue.Body = new MgooGps.DevicesAjax.SaveDevicesRequestBody();
            inValue.Body.UserID = UserID;
            inValue.Body.CategoryID = CategoryID;
            inValue.Body.IMEIs = IMEIs;
            inValue.Body.OverSpeed = OverSpeed;
            inValue.Body.IsImeis = IsImeis;
            MgooGps.DevicesAjax.SaveDevicesResponse retVal = ((MgooGps.DevicesAjax.DevicesAjaxSoap)(this)).SaveDevices(inValue);
            return retVal.Body.SaveDevicesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MgooGps.DevicesAjax.GetDevicesResponse MgooGps.DevicesAjax.DevicesAjaxSoap.GetDevices(MgooGps.DevicesAjax.GetDevicesRequest request) {
            return base.Channel.GetDevices(request);
        }
        
        public string GetDevices(int UserID, int PageNo, int PageCount, string SN, string TimeZones, int ExpDays) {
            MgooGps.DevicesAjax.GetDevicesRequest inValue = new MgooGps.DevicesAjax.GetDevicesRequest();
            inValue.Body = new MgooGps.DevicesAjax.GetDevicesRequestBody();
            inValue.Body.UserID = UserID;
            inValue.Body.PageNo = PageNo;
            inValue.Body.PageCount = PageCount;
            inValue.Body.SN = SN;
            inValue.Body.TimeZones = TimeZones;
            inValue.Body.ExpDays = ExpDays;
            MgooGps.DevicesAjax.GetDevicesResponse retVal = ((MgooGps.DevicesAjax.DevicesAjaxSoap)(this)).GetDevices(inValue);
            return retVal.Body.GetDevicesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MgooGps.DevicesAjax.GetDevicesByUserIDResponse MgooGps.DevicesAjax.DevicesAjaxSoap.GetDevicesByUserID(MgooGps.DevicesAjax.GetDevicesByUserIDRequest request) {
            return base.Channel.GetDevicesByUserID(request);
        }
        
        public string GetDevicesByUserID(int UserID, bool isFirst, string TimeZones) {
            MgooGps.DevicesAjax.GetDevicesByUserIDRequest inValue = new MgooGps.DevicesAjax.GetDevicesByUserIDRequest();
            inValue.Body = new MgooGps.DevicesAjax.GetDevicesByUserIDRequestBody();
            inValue.Body.UserID = UserID;
            inValue.Body.isFirst = isFirst;
            inValue.Body.TimeZones = TimeZones;
            MgooGps.DevicesAjax.GetDevicesByUserIDResponse retVal = ((MgooGps.DevicesAjax.DevicesAjaxSoap)(this)).GetDevicesByUserID(inValue);
            return retVal.Body.GetDevicesByUserIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MgooGps.DevicesAjax.GetGeofenceDevicesByUserIDResponse MgooGps.DevicesAjax.DevicesAjaxSoap.GetGeofenceDevicesByUserID(MgooGps.DevicesAjax.GetGeofenceDevicesByUserIDRequest request) {
            return base.Channel.GetGeofenceDevicesByUserID(request);
        }
        
        public string GetGeofenceDevicesByUserID(int UserID, bool isFirst, string TimeZones) {
            MgooGps.DevicesAjax.GetGeofenceDevicesByUserIDRequest inValue = new MgooGps.DevicesAjax.GetGeofenceDevicesByUserIDRequest();
            inValue.Body = new MgooGps.DevicesAjax.GetGeofenceDevicesByUserIDRequestBody();
            inValue.Body.UserID = UserID;
            inValue.Body.isFirst = isFirst;
            inValue.Body.TimeZones = TimeZones;
            MgooGps.DevicesAjax.GetGeofenceDevicesByUserIDResponse retVal = ((MgooGps.DevicesAjax.DevicesAjaxSoap)(this)).GetGeofenceDevicesByUserID(inValue);
            return retVal.Body.GetGeofenceDevicesByUserIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MgooGps.DevicesAjax.GetDeviceCountResponse MgooGps.DevicesAjax.DevicesAjaxSoap.GetDeviceCount(MgooGps.DevicesAjax.GetDeviceCountRequest request) {
            return base.Channel.GetDeviceCount(request);
        }
        
        public string GetDeviceCount(int UserID) {
            MgooGps.DevicesAjax.GetDeviceCountRequest inValue = new MgooGps.DevicesAjax.GetDeviceCountRequest();
            inValue.Body = new MgooGps.DevicesAjax.GetDeviceCountRequestBody();
            inValue.Body.UserID = UserID;
            MgooGps.DevicesAjax.GetDeviceCountResponse retVal = ((MgooGps.DevicesAjax.DevicesAjaxSoap)(this)).GetDeviceCount(inValue);
            return retVal.Body.GetDeviceCountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MgooGps.DevicesAjax.GetExpireDevicesResponse MgooGps.DevicesAjax.DevicesAjaxSoap.GetExpireDevices(MgooGps.DevicesAjax.GetExpireDevicesRequest request) {
            return base.Channel.GetExpireDevices(request);
        }
        
        public string GetExpireDevices(int UserID, string SN) {
            MgooGps.DevicesAjax.GetExpireDevicesRequest inValue = new MgooGps.DevicesAjax.GetExpireDevicesRequest();
            inValue.Body = new MgooGps.DevicesAjax.GetExpireDevicesRequestBody();
            inValue.Body.UserID = UserID;
            inValue.Body.SN = SN;
            MgooGps.DevicesAjax.GetExpireDevicesResponse retVal = ((MgooGps.DevicesAjax.DevicesAjaxSoap)(this)).GetExpireDevices(inValue);
            return retVal.Body.GetExpireDevicesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MgooGps.DevicesAjax.SaleDevicesResponse MgooGps.DevicesAjax.DevicesAjaxSoap.SaleDevices(MgooGps.DevicesAjax.SaleDevicesRequest request) {
            return base.Channel.SaleDevices(request);
        }
        
        public string SaleDevices(int SaleUserID, int UserID, string DeviceIDs, string ExpireDate, string PhoneNum, int isMany, string Remark, string TimeZones) {
            MgooGps.DevicesAjax.SaleDevicesRequest inValue = new MgooGps.DevicesAjax.SaleDevicesRequest();
            inValue.Body = new MgooGps.DevicesAjax.SaleDevicesRequestBody();
            inValue.Body.SaleUserID = SaleUserID;
            inValue.Body.UserID = UserID;
            inValue.Body.DeviceIDs = DeviceIDs;
            inValue.Body.ExpireDate = ExpireDate;
            inValue.Body.PhoneNum = PhoneNum;
            inValue.Body.isMany = isMany;
            inValue.Body.Remark = Remark;
            inValue.Body.TimeZones = TimeZones;
            MgooGps.DevicesAjax.SaleDevicesResponse retVal = ((MgooGps.DevicesAjax.DevicesAjaxSoap)(this)).SaleDevices(inValue);
            return retVal.Body.SaleDevicesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MgooGps.DevicesAjax.SearchDevicesResponse MgooGps.DevicesAjax.DevicesAjaxSoap.SearchDevices(MgooGps.DevicesAjax.SearchDevicesRequest request) {
            return base.Channel.SearchDevices(request);
        }
        
        public string SearchDevices(int UserID, string SNName, int SNTypeID, int OfflineType, int TimeTypeID, string StartTime, string EndTime, string TimeZones) {
            MgooGps.DevicesAjax.SearchDevicesRequest inValue = new MgooGps.DevicesAjax.SearchDevicesRequest();
            inValue.Body = new MgooGps.DevicesAjax.SearchDevicesRequestBody();
            inValue.Body.UserID = UserID;
            inValue.Body.SNName = SNName;
            inValue.Body.SNTypeID = SNTypeID;
            inValue.Body.OfflineType = OfflineType;
            inValue.Body.TimeTypeID = TimeTypeID;
            inValue.Body.StartTime = StartTime;
            inValue.Body.EndTime = EndTime;
            inValue.Body.TimeZones = TimeZones;
            MgooGps.DevicesAjax.SearchDevicesResponse retVal = ((MgooGps.DevicesAjax.DevicesAjaxSoap)(this)).SearchDevices(inValue);
            return retVal.Body.SearchDevicesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MgooGps.DevicesAjax.GetDevicesHistoryResponse MgooGps.DevicesAjax.DevicesAjaxSoap.GetDevicesHistory(MgooGps.DevicesAjax.GetDevicesHistoryRequest request) {
            return base.Channel.GetDevicesHistory(request);
        }
        
        public string GetDevicesHistory(int DeviceID, System.DateTime Start, System.DateTime End, string TimeZone, int ShowLBS) {
            MgooGps.DevicesAjax.GetDevicesHistoryRequest inValue = new MgooGps.DevicesAjax.GetDevicesHistoryRequest();
            inValue.Body = new MgooGps.DevicesAjax.GetDevicesHistoryRequestBody();
            inValue.Body.DeviceID = DeviceID;
            inValue.Body.Start = Start;
            inValue.Body.End = End;
            inValue.Body.TimeZone = TimeZone;
            inValue.Body.ShowLBS = ShowLBS;
            MgooGps.DevicesAjax.GetDevicesHistoryResponse retVal = ((MgooGps.DevicesAjax.DevicesAjaxSoap)(this)).GetDevicesHistory(inValue);
            return retVal.Body.GetDevicesHistoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MgooGps.DevicesAjax.GetDeviceHistoryByRoadOffsetResponse MgooGps.DevicesAjax.DevicesAjaxSoap.GetDeviceHistoryByRoadOffset(MgooGps.DevicesAjax.GetDeviceHistoryByRoadOffsetRequest request) {
            return base.Channel.GetDeviceHistoryByRoadOffset(request);
        }
        
        public string GetDeviceHistoryByRoadOffset(int DeviceID, string StartTime, string EndTime, string TimeZone, int ShowLBS) {
            MgooGps.DevicesAjax.GetDeviceHistoryByRoadOffsetRequest inValue = new MgooGps.DevicesAjax.GetDeviceHistoryByRoadOffsetRequest();
            inValue.Body = new MgooGps.DevicesAjax.GetDeviceHistoryByRoadOffsetRequestBody();
            inValue.Body.DeviceID = DeviceID;
            inValue.Body.StartTime = StartTime;
            inValue.Body.EndTime = EndTime;
            inValue.Body.TimeZone = TimeZone;
            inValue.Body.ShowLBS = ShowLBS;
            MgooGps.DevicesAjax.GetDeviceHistoryByRoadOffsetResponse retVal = ((MgooGps.DevicesAjax.DevicesAjaxSoap)(this)).GetDeviceHistoryByRoadOffset(inValue);
            return retVal.Body.GetDeviceHistoryByRoadOffsetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MgooGps.DevicesAjax.GetTrackingResponse MgooGps.DevicesAjax.DevicesAjaxSoap.GetTracking(MgooGps.DevicesAjax.GetTrackingRequest request) {
            return base.Channel.GetTracking(request);
        }
        
        public string GetTracking(int DeviceID, string TimeZone) {
            MgooGps.DevicesAjax.GetTrackingRequest inValue = new MgooGps.DevicesAjax.GetTrackingRequest();
            inValue.Body = new MgooGps.DevicesAjax.GetTrackingRequestBody();
            inValue.Body.DeviceID = DeviceID;
            inValue.Body.TimeZone = TimeZone;
            MgooGps.DevicesAjax.GetTrackingResponse retVal = ((MgooGps.DevicesAjax.DevicesAjaxSoap)(this)).GetTracking(inValue);
            return retVal.Body.GetTrackingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MgooGps.DevicesAjax.UpdateHireExpriDateResponse MgooGps.DevicesAjax.DevicesAjaxSoap.UpdateHireExpriDate(MgooGps.DevicesAjax.UpdateHireExpriDateRequest request) {
            return base.Channel.UpdateHireExpriDate(request);
        }
        
        public int UpdateHireExpriDate(string DeviceIDs, string EndTime, string TimeZone) {
            MgooGps.DevicesAjax.UpdateHireExpriDateRequest inValue = new MgooGps.DevicesAjax.UpdateHireExpriDateRequest();
            inValue.Body = new MgooGps.DevicesAjax.UpdateHireExpriDateRequestBody();
            inValue.Body.DeviceIDs = DeviceIDs;
            inValue.Body.EndTime = EndTime;
            inValue.Body.TimeZone = TimeZone;
            MgooGps.DevicesAjax.UpdateHireExpriDateResponse retVal = ((MgooGps.DevicesAjax.DevicesAjaxSoap)(this)).UpdateHireExpriDate(inValue);
            return retVal.Body.UpdateHireExpriDateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MgooGps.DevicesAjax.UpdateHireExpriDateDaysResponse MgooGps.DevicesAjax.DevicesAjaxSoap.UpdateHireExpriDateDays(MgooGps.DevicesAjax.UpdateHireExpriDateDaysRequest request) {
            return base.Channel.UpdateHireExpriDateDays(request);
        }
        
        public int UpdateHireExpriDateDays(int UserID, string DeviceIDs, int AddHireDays) {
            MgooGps.DevicesAjax.UpdateHireExpriDateDaysRequest inValue = new MgooGps.DevicesAjax.UpdateHireExpriDateDaysRequest();
            inValue.Body = new MgooGps.DevicesAjax.UpdateHireExpriDateDaysRequestBody();
            inValue.Body.UserID = UserID;
            inValue.Body.DeviceIDs = DeviceIDs;
            inValue.Body.AddHireDays = AddHireDays;
            MgooGps.DevicesAjax.UpdateHireExpriDateDaysResponse retVal = ((MgooGps.DevicesAjax.DevicesAjaxSoap)(this)).UpdateHireExpriDateDays(inValue);
            return retVal.Body.UpdateHireExpriDateDaysResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MgooGps.DevicesAjax.ChangeDevicesUserResponse MgooGps.DevicesAjax.DevicesAjaxSoap.ChangeDevicesUser(MgooGps.DevicesAjax.ChangeDevicesUserRequest request) {
            return base.Channel.ChangeDevicesUser(request);
        }
        
        public int ChangeDevicesUser(string DeviceIDs, int OldUserID, int NewUserID, string TimeZone) {
            MgooGps.DevicesAjax.ChangeDevicesUserRequest inValue = new MgooGps.DevicesAjax.ChangeDevicesUserRequest();
            inValue.Body = new MgooGps.DevicesAjax.ChangeDevicesUserRequestBody();
            inValue.Body.DeviceIDs = DeviceIDs;
            inValue.Body.OldUserID = OldUserID;
            inValue.Body.NewUserID = NewUserID;
            inValue.Body.TimeZone = TimeZone;
            MgooGps.DevicesAjax.ChangeDevicesUserResponse retVal = ((MgooGps.DevicesAjax.DevicesAjaxSoap)(this)).ChangeDevicesUser(inValue);
            return retVal.Body.ChangeDevicesUserResult;
        }
        
        public int DelDevice(int DeviceID) {
            return base.Channel.DelDevice(DeviceID);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MgooGps.DevicesAjax.ChangeDevicePasswordResponse MgooGps.DevicesAjax.DevicesAjaxSoap.ChangeDevicePassword(MgooGps.DevicesAjax.ChangeDevicePasswordRequest request) {
            return base.Channel.ChangeDevicePassword(request);
        }
        
        public int ChangeDevicePassword(int DeviceID, string OldPass, string NewPass) {
            MgooGps.DevicesAjax.ChangeDevicePasswordRequest inValue = new MgooGps.DevicesAjax.ChangeDevicePasswordRequest();
            inValue.Body = new MgooGps.DevicesAjax.ChangeDevicePasswordRequestBody();
            inValue.Body.DeviceID = DeviceID;
            inValue.Body.OldPass = OldPass;
            inValue.Body.NewPass = NewPass;
            MgooGps.DevicesAjax.ChangeDevicePasswordResponse retVal = ((MgooGps.DevicesAjax.DevicesAjaxSoap)(this)).ChangeDevicePassword(inValue);
            return retVal.Body.ChangeDevicePasswordResult;
        }
        
        public int InitDevicePassword(int DeviceID) {
            return base.Channel.InitDevicePassword(DeviceID);
        }
        
        public int UpdateDeviceGroupID(int DeviceID, int GroupID) {
            return base.Channel.UpdateDeviceGroupID(DeviceID, GroupID);
        }
    }
}
